### ISSUE TITLE
Support new Firefox sandboxing

### ISSUE THREAD

**Issue by ryanfeeley** [vladikoff/foxfire#4]
Can no longer open new profiles in the same browser. If I have Nightly open, I can't open another Nightly, but I can open another Firefox.

Possible to fix?

**Comment by vladikoff** [comment]
so another problem, somehow `./firefox -P` `./firefox -p /path/to/profile` is now broken in latest nightly 

🤷‍♂

**Comment by vladikoff** [comment]
this was fixed
